# Copyright 2017 Virgil Dupras
#
# This software is licensed under the "GPLv3" License as described in the "LICENSE" file,
# which should be included with this package. The terms are also available at
# http://www.gnu.org/licenses/gpl-3.0.html

from base64 import b64encode
from pathlib import Path
import sys
from optparse import OptionParser
import shutil
from multiprocessing import Pool
from xml.etree import ElementTree

from hscommon import sphinxgen
from hscommon.build import add_to_pythonpath
from hscommon import loc
import subprocess


def parse_args():
    usage = "usage: %prog [options]"
    parser = OptionParser(usage=usage)
    parser.add_option(
        "--clean",
        action="store_true",
        dest="clean",
        help="Clean build folder before building",
    )
    parser.add_option("--doc", action="store_true", dest="doc", help="Build only the help file (en)")
    parser.add_option("--alldoc", action="store_true", dest="all_doc", help="Build only the help file in all languages")
    parser.add_option("--loc", action="store_true", dest="loc", help="Build only localization")
    parser.add_option(
        "--updatepot",
        action="store_true",
        dest="updatepot",
        help="Generate .pot files from source code.",
    )
    parser.add_option(
        "--mergepot",
        action="store_true",
        dest="mergepot",
        help="Update all .po files based on .pot files.",
    )
    parser.add_option(
        "--normpo",
        action="store_true",
        dest="normpo",
        help="Normalize all PO files (do this before commit).",
    )
    parser.add_option(
        "--modules",
        action="store_true",
        dest="modules",
        help="Build the python modules.",
    )
    parser.add_option(
        "--resources",
        action="store_true",
        dest="resources",
        help="Regenerate qt/resources_data.py from qt/dg.qrc. Only needed after changing an image.",
    )
    (options, args) = parser.parse_args()
    return options


def build_one_help(language):
    print(f"Generating Help in {language}")
    current_path = Path(".").absolute()
    changelog_path = current_path.joinpath("help", "changelog")
    tixurl = "https://github.com/arsenetar/dupeguru/issues/{}"
    changelogtmpl = current_path.joinpath("help", "changelog.tmpl")
    conftmpl = current_path.joinpath("help", "conf.tmpl")
    help_basepath = current_path.joinpath("help", language)
    help_destpath = current_path.joinpath("build", "help", language)
    confrepl = {"language": language}
    sphinxgen.gen(
        help_basepath,
        help_destpath,
        changelog_path,
        tixurl,
        confrepl,
        conftmpl,
        changelogtmpl,
    )


def build_help():
    languages = ["en", "de", "fr", "hy", "ru", "uk"]
    # Running with Pools as for some reason sphinx seems to cross contaminate the output otherwise
    with Pool(len(languages)) as p:
        p.map(build_one_help, languages)


def build_localizations():
    loc.compile_all_po("locale")
    locale_dest = Path("build", "locale")
    if locale_dest.exists():
        shutil.rmtree(locale_dest)
    shutil.copytree("locale", locale_dest, ignore=shutil.ignore_patterns("*.po", "*.pot"))


def build_updatepot():
    print("Building .pot files from source files")
    print("Building core.pot")
    loc.generate_pot(["core"], Path("locale", "core.pot"), ["tr"])
    print("Building columns.pot")
    loc.generate_pot(["core"], Path("locale", "columns.pot"), ["coltr"])
    print("Building ui.pot")
    loc.generate_pot(["qt"], Path("locale", "ui.pot"), ["tr"], merge=True)


def build_mergepot():
    print("Updating .po files using .pot files")
    loc.merge_pots_into_pos("locale")


def build_normpo():
    loc.normalize_all_pos("locale")


def build_pe_modules():
    print("Building PE Modules")
    # Leverage setup.py to build modules
    subprocess.check_call([sys.executable, "setup.py", "build_ext", "--inplace"])


QRC_PATH = Path("qt", "dg.qrc")
RESOURCES_DATA_PATH = Path("qt", "resources_data.py")

RESOURCES_HEADER = """\
# This file is generated by build.py:build_qt_resources from qt/dg.qrc. Do not edit it.
#
# Regenerate with:
#     python build.py --resources
#
# It is committed rather than built, so that there is no resource build step left to fail
# silently, and so frozen builds keep working without images/ being bundled as data files.
# qt/tests/resources_test.py regenerates this and compares, so it cannot drift unnoticed.
# See qt/resources.py for why Qt's own .qrc system is not used.

RESOURCES = {
"""


def read_resource_manifest():
    """Parse qt/dg.qrc into {alias: Path}.

    dg.qrc is no longer compiled by pyrcc5 -- PyQt6 has no equivalent tool -- but it remains
    a perfectly good declarative manifest of alias to image, so it is kept as the input to
    our own generator rather than inventing a second format for eleven entries.
    """
    tree = ElementTree.parse(QRC_PATH)
    manifest = {}
    for elem in tree.iter("file"):
        alias = elem.get("alias")
        if not alias:
            raise ValueError(f"{QRC_PATH}: <file> entry without an alias: {elem.text}")
        # Paths in the .qrc are relative to the .qrc's own directory.
        manifest[alias] = (QRC_PATH.parent / elem.text).resolve()
    return manifest


def render_resources_module():
    """Return the text of qt/resources_data.py for the current images."""
    lines = [RESOURCES_HEADER]
    for alias, path in sorted(read_resource_manifest().items()):
        if not path.exists():
            raise FileNotFoundError(f"{QRC_PATH} references a missing file: {path}")
        encoded = b64encode(path.read_bytes()).decode("ascii")
        # Wrapped so the file stays diffable and within the project's line length.
        chunks = [encoded[i : i + 100] for i in range(0, len(encoded), 100)]
        lines.append(f"    {alias!r}: (\n")
        lines.extend(f'        "{chunk}"\n' for chunk in chunks)
        lines.append("    ),\n")
    lines.append("}\n")
    return "".join(lines)


def build_qt_resources():
    """Regenerate qt/resources_data.py from qt/dg.qrc and the images it names."""
    RESOURCES_DATA_PATH.write_text(render_resources_module(), encoding="utf-8")
    print(f"Wrote {RESOURCES_DATA_PATH}")


def build_normal():
    print("Building dupeGuru with UI qt")
    add_to_pythonpath(".")
    print("Building dupeGuru")
    build_pe_modules()
    print("Building localizations")
    build_localizations()
    # Resources are committed, not built here: see qt/resources.py. Use --resources after
    # changing an image.
    build_help()


def main():
    if sys.version_info < (3, 7):
        sys.exit("Python < 3.7 is unsupported.")
    options = parse_args()
    if options.clean and Path("build").exists():
        shutil.rmtree("build")
    if not Path("build").exists():
        Path("build").mkdir()
    if options.doc:
        build_one_help("en")
    elif options.all_doc:
        build_help()
    elif options.loc:
        build_localizations()
    elif options.updatepot:
        build_updatepot()
    elif options.mergepot:
        build_mergepot()
    elif options.normpo:
        build_normpo()
    elif options.modules:
        build_pe_modules()
    elif options.resources:
        build_qt_resources()
    else:
        build_normal()


if __name__ == "__main__":
    main()
